[package]
name = "koratabs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
svg = "0.17.0"
roxmltree = "0.20.0"
toml = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
hound = "3.5"
rustfft = "6.1"
image = "0.25.1"